<?php
//--------------------------------------------------------------------------//
/** @var \Magento\Framework\Session\Config\ConfigInterface $sessionConfig */
$sessionConfig = \Magento\Framework\App\ObjectManager::getInstance()->get(
    \Magento\Framework\Session\Config\ConfigInterface::class
);
//--------------------------------------------------------------------------//
/** @var $block \Magento\Framework\View\Element\Js\Cookie */
?>
<script type="text/x-magento-init">
{
    "*": {
        "mage/cookies": {
            "expires": null,
            "path": "<?= $block->escapeJs($block->getPath()) ?>",
            "domain": "<?= $block->escapeJs($block->getDomain()) ?>",
            "secure": <?= $sessionConfig->getCookieSecure() ? 'true' : 'false' ?>,
            "lifetime": "<?= $block->escapeJs($block->getLifetime()) ?>"
        }
    }
}</script>
<script type="text/javascript">
    window.cookiesConfig = window.cookiesConfig || {};
    window.cookiesConfig.secure = <?= $sessionConfig->getCookieSecure() ? 'true' : 'false' ?>;
    window.cookiesConfig.samesite = '<?= $sessionConfig->getCookieSameSite()?>';
</script>
