<?php
/**
 * Cookie settings initialization script
 *
 * @var $block \Magento\Framework\View\Element\Js\Cookie
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$isCookieSecure = $block->getSessionConfig()->getCookieSecure() ? 'true' : 'false';
$sameSite = $block->getSessionConfig()->getCookieSameSite();
$scriptString = "
    window.cookiesConfig = window.cookiesConfig || {};
    window.cookiesConfig.secure = $isCookieSecure;
    window.cookiesConfig.samesite = '<?= $sameSite ?>';
";
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
